spring:
  data:
    mongodb:
      uri: mongodb+srv://marketplace-user:marketplace123@marketplace-cluster.vu5awxj.mongodb.net/?retryWrites=true&w=majority&appName=marketplace-cluster
      auto-index-creation: true
      database: marketplace
  application:
    name: marketplace-backend
  main:
    allow-circular-references: true

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:your-email@gmail.com}
    password: ${EMAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  # Thymeleaf for email templates
  thymeleaf:
    prefix: classpath:/templates/email/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  # File upload configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

  # Static resource handling
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
      add-mappings: true

server:
  port: 8080

# Application specific config
app:
  name: Cosmic Marketplace
  url: ${APP_URL:http://localhost:5173}
  support:
    email: ${SUPPORT_EMAIL:support@cosmicmarketplace.com}

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789abcdefghijklmnopqrstuvwxyz}
  expiration: 86400000 # 24 hours

stripe:
  api-key: ${STRIPE_SECRET_KEY:sk_test_your_stripe_secret_key_here}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:pk_test_your_stripe_publishable_key_here}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_your_webhook_secret}

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

# File storage configuration
file:
  upload:
    dir: uploads/
    max-size: 10485760 # 10MB
    allowed-types: image/jpeg,image/jpg,image/png,image/gif

logging:
  level:
    com.marketplace: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.multipart: DEBUG
    org.springframework.mail: DEBUG

# Pagination defaults
pagination:
  default-page-size: 20
  max-page-size: 100

# Search configuration
search:
  max-results: 100
  suggestion-limit: 10

# Email settings
email:
  from-name: Cosmic Marketplace
  templates:
    welcome: welcome
    order-confirmation: order-confirmation
    order-status-update: order-status-update
    new-product: new-product
    promotion: promotion
    password-reset: password-reset